import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Header from "../pages/components/Header";

const lato = Lato({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["latin"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
